compatible with Catalina

diff --git a/mojavefonts b/mojavefonts
--- a/mojavefonts
+++ b/mojavefonts
@@ -2,13 +2,19 @@
 
 if [ "$(uname)" != Darwin ]
 then
-	echo 'uname(1) reports you are not running Darwin!'
+	echo 'uname(1) reports you are not running Darwin!' >&2
 	exit 1
 fi
 
-if [ "$(sw_vers -productVersion | cut -d. -f2)" != 14 ]
+version="$(sw_vers -productVersion | cut -d. -f2)"
+if [ -z "$version" ]
 then
-	echo 'You are not running macOS 10.14 Mojave!'
+	echo 'Error getting macOS version' >&2
+	exit 1
+fi
+if [ $version -lt 14 ]
+then
+	echo 'You are not running macOS 10.14 Mojave!' >&2
 	exit 1
 fi
 
