update for 42sh

diff --git a/vogtrans b/vogtrans
--- a/vogtrans
+++ b/vogtrans
@@ -1,35 +1,47 @@
-#!/bin/sh
+#!/bin/bash
 
-if [ ! -d "$PROJPATH" ]; then
-	echo "$0: missing \$PROJPATH env var"
-	exit 1
-fi
-if [ ! -d "$PROJPATH/Libft" -o ! -d "$PROJPATH/Get_Next_Line" ]; then
-	echo "$0: missing Libft or Get_Next_Line folder in \$PROJPATH"
-	exit 1
-fi
+# Check usage
 if [ ! -d "$1" -o -z "$2" ]; then
 	echo "usage: $0 source destination"
 	exit 1
 fi
 
+# Check PROJPATH
+if [ ! -d "$PROJPATH" ] && [ -h "$1/libft" -o -h "$1/libftreadline" ]; then
+	echo "$0: missing \$PROJPATH env var"
+	exit 1
+fi
+
+# Check libft in PROJPATH
+if [ ! -d "$PROJPATH/Libft" ] && [ -h "$1/libft" ]; then
+	echo "$0: missing Libft folder in \$PROJPATH"
+	exit 1
+fi
+
+# Preparations
 [ ! -d "$2" ] && mkdir "$2"
 rm -rf "$2/"*
 
+# Main
 echo "Copying main project"
 cp -a "$1"/* "$2"
 echo "Cleaning main project"
-rm -f "$2/README.md" "$2/libft"
+rm -f "$2/README.md"
 rm -rf "$2/misc"
 
-echo "Adding libft"
-cp -a "$PROJPATH/Libft" "$2/libft"
-echo "Cleaning libft"
-rm -rf "$2/libft/.git" "$2/libft/misc" "$2/libft/objs"
-rm -f "$2/libft/README.md" "$2/libft/auteur" "$2/libft/.oproj_config"
-make fclean -C "$2/libft" >/dev/null
+# libft
+if [ -h "$1/libft" ]; then
+	echo "Adding libft"
+	rm -f "$2/libft"
+	cp -a "$PROJPATH/Libft" "$2/libft"
+	echo "Cleaning libft"
+	rm -rf "$2/libft/.git" "$2/libft/misc" "$2/libft/objs"
+	rm -f "$2/libft/README.md" "$2/libft/auteur" "$2/libft/.oproj_config"
+	make fclean -C "$2/libft" >/dev/null
+fi
 
-if [ -d "$1"/libftreadline ]; then
+# libftreadline
+if [ -h "$1"/libftreadline ]; then
 	echo "Adding libftreadline"
 	rm -f "$2/libftreadline"
 	cp -a "$PROJPATH/libftreadline" "$2"
